Here is a list of what we will do in future:
(in random order)

- Upgrade Recordings: File View, to use syntax highliting and node collapse'ing
- Add "Varianting" So a button in "Recordings" that will say "Use this Response explicitly" it will add new Rule to Mock this response, not any other one.
- Upgrade Logger to show latest api calls in UI. was request mocked, was it proxied, what were details, etc.
- Refactor Code
- ???